set-option -g focus-events on
set-option -g mode-keys vi

# Alt-c to enter copy-mode
bind -n M-c copy-mode
# Start selection with v as in vim
bind -T copy-mode-vi v send -X begin-selection
# Yank with y as in vim
bind -T copy-mode-vi y send -X copy-selection-and-cancel
# Put with p as in vim
bind -n M-p paste-buffer

# Alt + | (pipe) to split vertically
bind -n M-| split-window -h \; display-message "Alt + |"
#  Alt + - (dash) to split horizontally
bind -n M-- split-window -v \; display-message "Alt + -"

# Alt + hjkl naviagates panes
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-h select-pane -L
bind -n M-l select-pane -R

# Alt + arrows resize panes
bind -n M-Down  resize-pane -D 1
bind -n M-Up    resize-pane -U 1
bind -n M-Left  resize-pane -L 1
bind -n M-Right resize-pane -R 1

# Alt+r to Reload tmux.conf
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded Tmux"
 


set -g status-bg "#005577"
set -g status-fg "#000000"
set -g status-left  "#[bg=#005577,fg=black] #S "
set -g status-right "#[bg=#005577,fg=black] %Y-%m-%d %H:%M "

## Updated: ArchReal 2026-04-18 16:29
